#!/bin/bash

__doko-echo(){
  echo ">>> DOKO: $1"
}

#docker

__build-images(){
  if [ -f "docker/build.sh" ]; then
    docker/build.sh
  else
    docker-compose build
  fi
}

# docker-compose
__dcp(){
  service=$1
  shift
  docker-compose run --rm $service $@
}

__doko-setup(){
  if [ -f "docker/setup.sh" ]; then
    docker/setup.sh
  else
    project=${PWD##*/}
    docker-compose up -d postgres
    __build-images
    docker-compose run --rm web bundle exec rake db:setup
    docker-compose up
  fi
}

__doko-troubleshoot(){
  rails_server_pid_file="tmp/pids/server.pid"
  if [ -f $rails_server_pid_file ]; then
    __doko-echo "Removing Rails server PID file"
    rm $rails_server_pid_file
  fi
  docker-compose stop web
  docker-compose rm -f web
  doko up
}

__doko-bundle-exec(){
  docker-compose run --rm web bundle exec $@
}

__doko-clean-containers(){
  read -p "Do you want to remove all exited containers? (y/n) " answer
  if [ "$answer" == "y" ]; then
    __doko-echo "Removing containers exited weeks ago.";
    docker ps -a | grep 'Exited' | grep 'weeks ago' | awk '{print $1}' | xargs docker rm
  fi
}

__doko-clean-images(){
  read -p "Do you want to remove dangling images? (y/n) " answer
  if [ "$answer" == "y" ]; then
    __doko-echo "Removing danglign images.";
    docker rmi $(docker images -f "dangling=true" -q)
  fi
}

__doko-upgrade(){
  __doko-echo "Upgrading..."
  curl -s -o /usr/local/bin/doko https://raw.githubusercontent.com/pedrofernandezm/doko/master/doko
  chmod +x /usr/local/bin/doko
  __doko-exec version
}

__doko-exec(){
  case $1 in
  upgrade)
    __doko-upgrade
    ;;
  version)
    __doko-echo "version 0.3"
    ;;
  clean)
    __doko-clean-containers
    __doko-clean-images
    ;;
  setup)
    __doko-setup
    ;;
  build)
    __build-images
    ;;
  troubleshoot)
    __doko-troubleshoot
    ;;
  rake|rails)
    __doko-bundle-exec $@
    ;;
  npm)
    __dcp web $@
    ;;
  stop|ps|rm|up)
    docker-compose $@
    ;;
  *)
    __doko-echo "Unknown command."
    ;;
  esac
}

__doko-exec $@
